#!/usr/bin/env python

import sys
import mocha

from mocha.parser import MochaParser
from mocha.generator import JavaClassGenerator


def main():
    sys.setrecursionlimit(5000)

    ifilename, ofilename = mocha.parse_input(sys.argv[1:])

    package_name = mocha.build_package_name(ifilename)
    class_name = mocha.build_class_name(package_name)

    parser = MochaParser()
    generator = JavaClassGenerator()

    ast = parser.parse_file(ifilename)

    if ofilename is "":
        print generator.generate(package_name, class_name, ast)
    else:
        with open(ofilename, "w") as java_file:
            java_file.write(generator.generate(package_name, class_name, ast))

if __name__ == "__main__":
    main()

